# COMMON APPLICATION PROPERTIES

# start services on random port by default
server.port: 0

# database init, supports mysql too
petclinic:
  database: hsqldb

spring:
  datasource:
    data: classpath*:db/${petclinic.database}/data.sql
  sleuth:
    sampler:
      percentage: 1.0
  jpa:
    hibernate:
      ddl-auto: create-drop
      show_sql: true
      use_sql_comments: true
      format_sql: true
    properties:
      hibernate:
        type: trace

# Spring Boot 1.5 makes actuator secure by default
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: '*'

# Logging
logging.level.org.springframework: INFO
