# COMMON APPLICATION PROPERTIES

# start services on random port by default
server.port: 0

# database init, supports mysql too
petclinic.database: hsqldb
spring:
  datasource:
    schema: classpath*:db/${petclinic.database}/schema.sql
    data: classpath*:db/${petclinic.database}/data.sql
  sleuth:
    sampler:
      percentage: 1.0

# JPA
spring.jpa.hibernate.ddl-auto: none

# Spring Boot 1.5 makes actuator secure by default
management.security.enabled: false

# Logging
logging.level.org.springframework: INFO

# OAuth2 security
security:
  oauth2:
    client:
      client-id: 0oaew70vj3FfdNqht0h7
      client-secret: M-MU7dMUVvK8B0ndrS8s1TnflLfSdYqVTbbxCFTr
      access-token-uri: https://dev-154532.oktapreview.com/oauth2/default/v1/token
      user-authorization-uri: https://dev-154532.oktapreview.com/oauth2/default/v1/authorize
      scope: openid profile email
    resource:
      filter-order: 3
      user-info-uri: https://dev-154532.oktapreview.com/oauth2/default/v1/userinfo
      token-info-uri: https://dev-154532.oktapreview.com/oauth2/default/v1/introspect
      prefer-token-info: false
